version: '2'

services:
  movievotingcoremysql:
    image: vsgdev/movievotingcoremysql:1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: vsgdev/mysql-mv:1.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd123
      MYSQL_DATABASE: Movie
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/opt/mysql/data

volumes:
  db-data:
    driver: "vsphere"
    driver_opts:
      Capacity: "2G"
      VolumeStore: "default"

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.0.0/16

